LibraryManagement/Models/Book.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
       
    
        public int ID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid title")]
        public string Title { get; set; }
        public string Thumbnail { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid price")]
        [RegularExpression(@"^\$?(\d{1,3}(\,\d{3})*|(\d+))(\.\d{2})?$", ErrorMessage = "Please enter digit")]
        public float Price { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid available book")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Please enter digit")]
        public int AvailableBook { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a valid description")]
        public string Description { get; set; }
        [Required]
        public int AuthorID { get; set; }
        public IList<SelectListItem> AvailableAuthors { get; set; }
        [Required]
        public int CategoryID { get; set; }
        public IList<SelectListItem> AvailableCategories { get; set; }

        public Book()
        {
            this.BorrowedDetails = new HashSet<BorrowedDetail>();
            AvailableAuthors = new List<SelectListItem>();
            AvailableCategories = new List<SelectListItem>();
        }

        public HttpPostedFileBase ImageFile { get; set; }
        public virtual Author Author { get; set; }
        public virtual BookCategory BookCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowedDetail> BorrowedDetails { get; set; }
    }
}

LibraryManagement/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClosedXML.Excel;
using LibraryManagement.Models;
using PagedList;
using System.Linq.Dynamic;
using System.Data.Entity.Validation;
using System.ComponentModel.DataAnnotations;

namespace LibraryManagement.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private LibraryEntities _db = new LibraryEntities();
        // GET: Member
        [HttpGet]
        public ActionResult Index(int? page, int? size, string sortProperty, string sortOrder, string key)
        {
            ViewBag.title = "Books";
            if (page == null) page = 1;
            //add sortOrder to view bag
            if (sortOrder == "asc")
            {
                ViewBag.sortOrder = "desc";
            }
            else if (sortOrder == "desc")
            {
                ViewBag.sortOrder = "";
            }
            else
            {
                ViewBag.sortOrder = "asc";
            }
            //default sort is sort id
            if (sortProperty == null)
            {
                sortProperty = "id";
                ViewBag.sortOrder = "";
            }
            ViewBag.sortProperty = sortProperty;
            ViewBag.currentSize = size;
            var properties = typeof(Book).GetProperties();
            List<Tuple<string, bool>> list = new List<Tuple<string, bool>>();
            foreach (var item in properties)
            {
                var isVirtual = item.GetAccessors()[0].IsVirtual;

                if (item.Name == "BorrowedDetails") { continue; }
                if (item.Name == "Author") { continue; }
                if (item.Name == "BookCategory") { continue; }
                if (item.Name == "ImageFile") { continue; }
                if (item.Name == "AvailableAuthors") { continue; }
                if (item.Name == "AvailableCategories") { continue; }
                if (item.Name == "AuthorID") { isVirtual = true; }
                if (item.Name == "CategoryID") { isVirtual = true; }
                if (item.Name == "Thumbnail") { isVirtual = true; }
                Tuple<string, bool> t = new Tuple<string, bool>(item.Name, isVirtual);
                list.Add(t);
            }
            //initial sort heading
            foreach (var item in list)
            {
                //create heading table with non virtual part
                if (!item.Item2)
                {
                    if (sortOrder == "desc" && sortProperty == item.Item1)
                    {
                        ViewBag.Headings += "<th><a href='/book/page/" + page + "?size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
                       ViewBag.sortOrder + "&key=" + key + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort-desc'></i></th></a></th>";
                    }
                    else if (sortOrder == "asc" && sortProperty == item.Item1)
                    {
                        ViewBag.Headings += "<th><a href='/book/page/" + page + "?size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
                            ViewBag.sortOrder + "&key=" + key + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort-asc'></a></th>";
                    }
                    else
                    {
                        ViewBag.Headings += "<th><a href='/book/page/" + page + "?size=" + ViewBag.currentSize + "&sortProperty=" + item.Item1 + "&sortOrder=" +
                           ViewBag.sortOrder + "&key=" + key + "'>" + item.Item1 + "<i class='fa fa-fw fa-sort'></a></th>";
                    }

                }
                else
                {
                    ViewBag.Headings += "<th>" + item.Item1 + "</th>";
                }
            }
            //initial dropdown list size
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "5", Value = "5" });
            items.Add(new SelectListItem { Text = "10", Value = "10" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });
            items.Add(new SelectListItem { Text = "25", Value = "25" });
            items.Add(new SelectListItem { Text = "50", Value = "50" });
            items.Add(new SelectListItem { Text = "100", Value = "100" });
            items.Add(new SelectListItem { Text = "200", Value = "200" });
            foreach (var item in items)
            {
                if (item.Value == size.ToString()) item.Selected = true;
            }
            ViewBag.size = items;
            int pageNumber = (page ?? 1);
            int pageSize = (size ?? 5);
            //get all authors 
            var books = from b in _db.Books
                        select b;
            //check authors list is empty
            if (books.Count() == 0)
            {
                TempData["message"] = $"Not found anything in system!";
                TempData["error"] = true;
                return View(books.ToPagedList(pageNumber, pageSize));
            }

            //filter author with key search
            if (!String.IsNullOrEmpty(key))
            {
                books = books.Where(a => (a.ID + " ").Contains(key)).OrderBy(a => a.ID);
                ViewBag.searchValue = key;
            }

            //sort using dynamic linq
            if (sortOrder == "desc")
            {
                books = books.OrderBy(sortProperty + " desc");
            }
            else if (sortOrder == "asc")
            {
                books = books.OrderBy(sortProperty);
            }
            else
            {
                //default is sort by id
                books = books.OrderBy("id");
            }
            return View(books.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Add()
        {
            var model = new Book { AvailableAuthors = getAuthors(), AvailableCategories = getCategories() };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Book book)
        {
            if (ModelState.IsValid)
            {
                book = uploadImage(book);
                _db.Books.Add(book);
                _db.SaveChanges();
                ModelState.Clear();
                TempData["message"] = $"Add book successfully!";
                return RedirectToAction("Index", new { key = book.ID + " " });
            }
            book.AvailableAuthors = getAuthors();
            book.AvailableCategories = getCategories();
            return View(book);
        }


        public ActionResult Edit(int? id)
        {
            var book = (from a in _db.Books where a.ID == id select a).SingleOrDefault();
            if (id == null || book == null)
            {
                TempData["message"] = $"Update fail, Cannot found that Books in system!";
                TempData["error"] = true;
                return RedirectToAction("Index");
            }
            book.AvailableAuthors = getAuthors();
            book.AvailableCategories = getCategories();
            return View(book);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {

                if (book.ImageFile == null)
                {
                    var oldThumnail = ((from a in _db.Books where a.ID == book.ID select a).SingleOrDefault()).Thumbnail;
                    book.Thumbnail = oldThumnail;
                    book = uploadImage(book);
                }
                else
                {
                    book = uploadImage(book);
                    _db.Entry(book).State = EntityState.Modified;
                }
                _db.SaveChanges();
                TempData["message"] = $"Update books successfully!";
                return RedirectToAction("Index", new { key = book.ID + " " });
            }
            book.AvailableAuthors = getAuthors();
            book.AvailableCategories = getCategories();
            return View(book);
        }

        public ActionResult Delete(int? id)
        {
            var book = (from b in _db.Books where b.ID == id select b).SingleOrDefault();
            if (id == null || book == null)
            {
                TempData["message"] = $"Delete fail, Cannot found that Book in system!";
                TempData["error"] = true;
                return RedirectToAction("Index");
            }
            _db.Books.Remove(book);
            _db.SaveChanges();
            TempData["message"] = $"Delete Books {id} - {book.Title} successfully!";
            return RedirectToAction("Index");
        }

        public FileResult Export()
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[8] { new DataColumn("id"),
                                                     new DataColumn("title"),
            new DataColumn("thumbnail"),
            new DataColumn("price"),
            new DataColumn("available_book"),
            new DataColumn("description"),
            new DataColumn("author_id"),
            new DataColumn("category_id"),
            });
            var books = from b in _db.Books
                        select b;
            foreach (var book in books)
            {
                dt.Rows.Add(book.ID, book.Title, book.Thumbnail, book.Price, book.AvailableBook, book.Description, book.AuthorID, book.CategoryID);
            }
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                DateTime today = DateTime.Today;
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);

LibraryManagement/Views/Book/Add.cshtml
@{
    ViewBag.Title = "Book-Add";
}
@model LibraryManagement.Models.Book
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Add book form
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("Add", "Book", FormMethod.Post, new
                        { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                @Html.LabelFor(Model => Model.AuthorID, "Author")
                                @Html.DropDownListFor(Model => Model.AuthorID, Model.AvailableAuthors, new { @class = "form-control" })
                                @Html.ValidationMessageFor(Model => Model.AuthorID, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(Model => Model.CategoryID, "Category")
                                @Html.DropDownListFor(Model => Model.CategoryID, Model.AvailableCategories, new { @class = "form-control" })
                                @Html.ValidationMessageFor(Model => Model.CategoryID, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(b => b.Title, "Title")
                                @Html.TextBoxFor(b => b.Title, "", new { @class = "form-control", @placeholder = "Title" })
                                @Html.ValidationMessageFor(b => b.Title, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(b => b.Price, "Price")
                                @Html.TextBoxFor(b => b.Price, "", new { @class = "form-control", @placeholder = "Price" })
                                @Html.ValidationMessageFor(b => b.Price, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(b => b.AvailableBook, "Available Book")
                                @Html.TextBoxFor(b => b.AvailableBook, null, new { @class = "form-control", @placeholder = "Address" })
                                @Html.ValidationMessageFor(b => b.AvailableBook, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(b => b.Description, "Description")
                                @Html.TextAreaFor(b => b.Description, new { @class = "form-control", @placeholder = "Description" })
                                @Html.ValidationMessageFor(b => b.Description, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(b => b.Thumbnail, "Thumbnail")
                                <p id="p-image-contain"><img id="image-contain" src="" style="width: 150px; height: 150px;" alt="Image"></p>
                                @Html.TextBoxFor(b => b.ImageFile, new { @type = "file", @class = "form-control" })
                                @Html.ValidationMessageFor(b => b.Thumbnail, null, new { @class = "text-danger" })
                            </div>
                            <button type="submit" class="btn btn-primary">Add Book</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        if ($('#image-contain').attr('src') === '') {
            $('img').remove();
        }

        $("#ImageFile").change(function () {
            $('#p-image-contain').append('<img id="image-contain" src="" style="width: 150px; height: 150px;" alt="Image"></img>');
            showImage(this);
        });
    });

    function showImage(fileInput) {
        file = fileInput.files[0];
        reader = new FileReader();

        reader.onload = function (e) {
            $("#image-contain").attr('src', e.target.result);
        };
        reader.readAsDataURL(file);
    }
</script>

LibraryManagement/Views/Book/Edit.cshtml
@model LibraryManagement.Models.Book
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Update Book ID @Model.ID
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        @using (Html.BeginForm("Edit", "Book", FormMethod.Post, new
                        { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                @Html.HiddenFor(Model => Model.ID)
                                @Html.LabelFor(Model => Model.AuthorID, "Author")
                                @Html.DropDownListFor(Model => Model.AuthorID, Model.AvailableAuthors, new { @class = "form-control" })
                                @Html.ValidationMessageFor(b => b.AuthorID, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(Model => Model.CategoryID, "Category")
                                @Html.DropDownListFor(Model => Model.CategoryID, Model.AvailableCategories, new { @class = "form-control" })
                                @Html.ValidationMessageFor(Model => Model.CategoryID, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(b => b.Title, "Title")
                                @Html.TextBoxFor(b => b.Title, null, new { @class = "form-control" })
                                @Html.ValidationMessageFor(b => b.Title, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(b => b.Price, "Price")
                                @Html.TextBoxFor(b => b.Price, null, new { @class = "form-control" })
                                @Html.ValidationMessageFor(b => b.Price, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(b => b.AvailableBook, "Available Book")
                                @Html.TextBoxFor(b => b.AvailableBook, null, new { @class = "form-control" })
                                @Html.ValidationMessageFor(b => b.AvailableBook, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(b => b.Description, "Description")
                                @Html.TextAreaFor(b => b.Description, new { @class = "form-control" })
                                @Html.ValidationMessageFor(b => b.Description, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(b => b.Thumbnail, "Thumbnail")
                                @*@Html.TextBoxFor(b => b.thumbnail, new { @type = "text",style="display:none",@class = "form-control" })*@
                                <p id="p-image-contain"><img id="image-contain" src="@Model.Thumbnail" style="width: 150px; height: 150px;" alt="Image"></p>
                                <input type="file" id="image" name="ImageFile" value="">
                                @Html.ValidationMessageFor(b => b.Thumbnail, null, new { @class = "text-danger" })
                            </div>
                            <button type="submit" class="btn btn-info">Update</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    $("#image").change(function () {
        showImage(this);
    });

    function showImage(fileInput) {
        file = fileInput.files[0];
        reader = new FileReader();
        reader.onload = function (e) {
            $("#image-contain").attr('src', e.target.result);
        };
        reader.readAsDataURL(file);
    }
</script>

LibraryManagement/Views/Book/Index.cshtml
@model PagedList.IPagedList<LibraryManagement.Models.Book>
@using PagedList.Mvc;
<div class="row">
    @if (TempData["message"] != null)
    {
        var className = "alert text-center " + (@TempData["error"] != null ? "alert-danger" : "alert-success");
        <p class="@className">
            @TempData["message"]
        </p>
    }
    <div class="col-sm-9 mb-1">
        <form action="/Book/Index" method="GET">
            <div class="col-sm-5 pl-0">
                @Html.TextBox("key", null, new { @class = "form-control input-sm" })
                @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
                @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
            </div>
            <div class="col-sm-7">
                <input class="btn btn-primary" type="submit" value="Search" />
                @Html.ActionLink("Clear", "Index", "Book", null, new { @class = "btn btn-default" })
                <a href="@Url.Action("Add", "Book")" class="btn btn-success">
                    <i class="fa fa-plus"></i>
                    Add New
                </a>
                <a href="@Url.Action("Export", "Book")" class="btn btn-info"><i class="fa fa-download" aria-hidden="true"></i> Export to excel</a>
            </div>
        </form>
        @*@using (Html.BeginForm("Index", "Authors", FormMethod.Get)) {
                <div class="col-sm-5 pl-0">
                    @Html.TextBox("key", null, new { @class = "form-control input-sm" })
                </div>
                <div class="col-sm-7">
                    <input class="btn btn-primary" type="submit" value="Search" />
                    @Html.ActionLink("Clear", "Index", "Authors", null, new { @class = "btn btn-default" })
                    <a href="@Url.Action("Add", "Authors")" class="btn btn-success">
                        <i class="fa fa-plus"></i>
                        Add New
                    </a>
                </div>
            }*@
    </div>
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                All Books in library
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover"
                           id="dataTables-example">
                        <thead>
                            <tr class="center">
                                @Html.Raw(ViewBag.Headings)
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var book in Model)
                            {
                            <tr>
                                <td>@book.ID</td>
                                <td>@book.Title</td>
                                <td>
                                    <img src="@book.Thumbnail" style="width: 150px; height: 150px">
                                </td>
                                <td>@book.Price</td>
                                <td>@book.AvailableBook</td>
                                <td>@book.Description</td>
                                <td>@book.Author.AuthorName</td>
                                <td>@book.BookCategory.CategoryName</td>
                                <td>
                                    <a href="@Url.Action("Edit","Book",new {id=book.ID})" class="btn btn-primary"><i class="fa fa-pencil-square-o"></i> </a>
                                    <a href="@Url.Action("Delete","Book",new {id=book.ID})" onclick="deleteFunction(event, @book.ID)" class="btn btn-danger"><i class="fa fa-trash"></i>                                                    </a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        @*@using (Html.BeginForm("Index", "Authors", FormMethod.Get)) {
                <p class="m-20" style="width: 75px">
                    @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @class = "form-control", @onchange = "this.form.submit();" })
                </p>
            }*@
        <form action="/Book/Index" method="GET">
            <p class="m-20" style="width: 75px">
                @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @class = "form-control", @onchange = "this.form.submit();" })
                @Html.Hidden("sortProperty", (object)ViewBag.sortProperty)
                @Html.Hidden("sortOrder", (object)ViewBag.sortOrder)
                @Html.Hidden("key", (object)ViewBag.searchValue)
            </p>
        </form>
    </div>
    <div class="col-lg-6">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("Index",
            new {
                page,
                size = ViewBag.currentSize,
                sortProperty = ViewBag.sortProperty,
                sortOrder = ViewBag.sortProperty,
                key = ViewBag.searchValue,
            }))
    </div>

</div>


<script>
    function deleteFunction(event, id) {
        var { origin } = window.location;
        event.preventDefault();
        swal({
            title: "Do you want to delete Book " + id + "?",
            text: "",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        }).then((willDelete) => {
            if (willDelete) {

                window.location = `${origin}/Book/Delete/${id}`;
            }
        });
    }
</script>